name: flutterwebapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  webview_flutter: ^4.13.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  file_picker: ^10.3.1
  permission_handler: ^11.1.0

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/images/